package main

import (
	"encoding/json"
	"fmt"
	"html"
	"io"
	"net/http"
	"strings"
)

// RenderHTML renders a thread as a standalone HTML file
func RenderHTML(thread *Thread, embedImages bool) (string, error) {
	css := getHTMLCSS()
	js := getHTMLJS()

	var sb strings.Builder

	// HTML Header
	sb.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>`)
	sb.WriteString(html.EscapeString(thread.Title))
	sb.WriteString(`</title>
    <style>
`)
	sb.WriteString(css)
	sb.WriteString(`
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>`)
	sb.WriteString(html.EscapeString(thread.Title))
	sb.WriteString(`</h1>
            <div class="meta">
                <a href="https://x.com/`)
	sb.WriteString(thread.Author.Username)
	sb.WriteString(`" target="_blank" class="author">
                    @`)
	sb.WriteString(thread.Author.Username)
	sb.WriteString(`
                </a>
                <span class="tweet-count">`)
	sb.WriteString(fmt.Sprintf("%d tweets", len(thread.Tweets)))
	sb.WriteString(`</span>
            </div>
        </div>

        <div class="tweets">
`)

	// Render each tweet
	for _, tweet := range thread.Tweets {
		sb.WriteString(renderTweetHTML(tweet, embedImages))
	}

	sb.WriteString(`
        </div>

        <div class="footer">
            <p>Generated by tweet2blog • View on <a href="`)
	sb.WriteString(thread.URL)
	sb.WriteString(`" target="_blank">X/Twitter</a></p>
        </div>
    </div>

    <script>
`)
	sb.WriteString(js)
	sb.WriteString(`
    </script>
</body>
</html>
`)

	return sb.String(), nil
}

// renderTweetHTML renders a single tweet as HTML
func renderTweetHTML(tweet *Tweet, embedImages bool) string {
	var sb strings.Builder

	sb.WriteString(`            <div class="tweet">
                <div class="tweet-header">
                    <a href="https://x.com/`)
	sb.WriteString(tweet.Author.Username)
	sb.WriteString(`" target="_blank" class="user-link">
                        <strong>`)
	sb.WriteString(html.EscapeString(tweet.Author.Name))
	sb.WriteString(`</strong>
                        <span class="username">@`)
	sb.WriteString(tweet.Author.Username)
	sb.WriteString(`</span>
                    </a>
                    <span class="verified">`)
	if tweet.Author.Verified {
		sb.WriteString("✓")
	}
	sb.WriteString(`</span>
                </div>

                <div class="tweet-content">
                    <p>`)
	sb.WriteString(html.EscapeString(tweet.Text))
	sb.WriteString(`</p>
`)

	// Render media
	if len(tweet.Attachments.Media) > 0 {
		sb.WriteString(`                    <div class="media">
`)
		for _, media := range tweet.Attachments.Media {
			sb.WriteString(renderMediaHTML(media, embedImages))
		}
		sb.WriteString(`                    </div>
`)
	}

	// Render URLs
	if len(tweet.Attachments.URLs) > 0 {
		sb.WriteString(`                    <div class="urls">
`)
		for _, u := range tweet.Attachments.URLs {
			sb.WriteString(`                        <a href="`)
			sb.WriteString(html.EscapeString(u))
			sb.WriteString(`" target="_blank" rel="noopener">`)
			sb.WriteString(html.EscapeString(u))
			sb.WriteString(`</a><br>
`)
		}
		sb.WriteString(`                    </div>
`)
	}

	sb.WriteString(`                </div>

                <div class="tweet-footer">
                    <span class="date">`)
	sb.WriteString(tweet.CreatedAt.Format("Jan 2, 2006 • 3:04 PM"))
	sb.WriteString(`</span>
                    <div class="metrics">
                        <a href="https://x.com/`)
	sb.WriteString(tweet.Author.Username)
	sb.WriteString(`/status/`)
	sb.WriteString(tweet.ID)
	sb.WriteString(`" target="_blank">View on X</a>
                    </div>
                </div>
            </div>
`)

	return sb.String()
}

// renderMediaHTML renders media elements
func renderMediaHTML(media Media, embedImages bool) string {
	var sb strings.Builder

	switch media.Type {
	case "photo":
		sb.WriteString(`                        <div class="media-item">
                            <img src="`)
		if embedImages {
			// In real implementation, would fetch and encode as data URL
			sb.WriteString(media.URL)
		} else {
			sb.WriteString(html.EscapeString(media.URL))
		}
		sb.WriteString(`" alt="`)
		sb.WriteString(html.EscapeString(media.AltText))
		sb.WriteString(`" loading="lazy">
                        </div>
`)
	case "video", "animated_gif":
		sb.WriteString(`                        <div class="media-item">
                            <div class="video-placeholder">
                                <a href="`)
		sb.WriteString(html.EscapeString(media.URL))
		sb.WriteString(`" target="_blank">
                                    <img src="`)
		sb.WriteString(html.EscapeString(media.Preview))
		sb.WriteString(`" alt="Video thumbnail" loading="lazy">
                                    <div class="play-icon">▶</div>
                                </a>
                            </div>
                        </div>
`)
	}

	return sb.String()
}

// getHTMLCSS returns the embedded CSS
func getHTMLCSS() string {
	return `
:root {
    --bg-primary: #ffffff;
    --bg-secondary: #f7f9fa;
    --text-primary: #0f1419;
    --text-secondary: #536471;
    --border-color: #cfd9de;
    --link-color: #1d9bf0;
    --hover-bg: #f7f9fa;
}

@media (prefers-color-scheme: dark) {
    :root {
        --bg-primary: #000000;
        --bg-secondary: #16181c;
        --text-primary: #e7e9ea;
        --text-secondary: #71767b;
        --border-color: #2f3336;
        --link-color: #1d9bf0;
        --hover-bg: #16181c;
    }
}

* {
    box-sizing: border-box;
}

body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
    background-color: var(--bg-primary);
    color: var(--text-primary);
    margin: 0;
    padding: 0;
    line-height: 1.5;
}

.container {
    max-width: 600px;
    margin: 0 auto;
    padding: 20px;
}

.header {
    margin-bottom: 40px;
    padding-bottom: 20px;
    border-bottom: 1px solid var(--border-color);
}

.header h1 {
    margin: 0 0 10px 0;
    font-size: 28px;
    font-weight: 700;
    word-wrap: break-word;
}

.meta {
    display: flex;
    gap: 16px;
    font-size: 14px;
    color: var(--text-secondary);
}

.author {
    color: var(--link-color);
    text-decoration: none;
    font-weight: 600;
}

.author:hover {
    text-decoration: underline;
}

.tweet {
    padding: 16px 0;
    border-bottom: 1px solid var(--border-color);
    transition: background-color 0.2s;
}

.tweet:hover {
    background-color: var(--hover-bg);
    border-radius: 8px;
    padding: 16px;
    margin: 0 -16px;
    width: calc(100% + 32px);
}

.tweet-header {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 12px;
}

.user-link {
    display: flex;
    align-items: center;
    gap: 8px;
    text-decoration: none;
    color: var(--text-primary);
}

.user-link strong {
    font-weight: 600;
}

.user-link:hover strong {
    color: var(--link-color);
}

.username {
    color: var(--text-secondary);
    font-size: 14px;
}

.verified {
    color: var(--link-color);
    font-size: 14px;
}

.tweet-content {
    margin-bottom: 12px;
    word-wrap: break-word;
    white-space: pre-wrap;
}

.tweet-content p {
    margin: 0 0 12px 0;
    font-size: 15px;
    line-height: 1.5;
}

.media {
    margin: 12px 0;
    border-radius: 16px;
    overflow: hidden;
}

.media-item {
    margin-bottom: 12px;
}

.media-item img {
    max-width: 100%;
    height: auto;
    border-radius: 16px;
    display: block;
}

.video-placeholder {
    position: relative;
    background-color: var(--bg-secondary);
    border-radius: 16px;
    overflow: hidden;
    aspect-ratio: 16/9;
}

.video-placeholder a {
    display: block;
    width: 100%;
    height: 100%;
    position: relative;
}

.video-placeholder img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    margin: 0;
}

.play-icon {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 48px;
    color: white;
    text-shadow: 0 0 8px rgba(0, 0, 0, 0.5);
}

.urls {
    margin-top: 12px;
    padding: 12px;
    background-color: var(--bg-secondary);
    border-radius: 12px;
    border-left: 4px solid var(--link-color);
}

.urls a {
    color: var(--link-color);
    text-decoration: none;
    word-break: break-all;
    font-size: 13px;
}

.urls a:hover {
    text-decoration: underline;
}

.tweet-footer {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 13px;
    color: var(--text-secondary);
    margin-top: 12px;
}

.date {
    display: block;
}

.metrics {
    display: flex;
    gap: 12px;
}

.metrics a {
    color: var(--link-color);
    text-decoration: none;
}

.metrics a:hover {
    text-decoration: underline;
}

.footer {
    text-align: center;
    color: var(--text-secondary);
    font-size: 12px;
    margin-top: 40px;
    padding-top: 20px;
    border-top: 1px solid var(--border-color);
}

.footer a {
    color: var(--link-color);
    text-decoration: none;
}

.footer a:hover {
    text-decoration: underline;
}

@media (max-width: 600px) {
    .container {
        padding: 12px;
    }

    .header h1 {
        font-size: 20px;
    }

    .tweet {
        padding: 12px 0;
    }
}
`
}

// getHTMLJS returns the embedded JavaScript
func getHTMLJS() string {
	return `
// Dark mode toggle
(function() {
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    
    if (prefersDark) {
        document.documentElement.style.colorScheme = 'dark';
    }

    // Lazy load images
    if ('IntersectionObserver' in window) {
        const images = document.querySelectorAll('img[loading="lazy"]');
        const imageObserver = new IntersectionObserver((entries, observer) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    const img = entry.target;
                    img.src = img.src;
                    imageObserver.unobserve(img);
                }
            });
        });

        images.forEach(img => imageObserver.observe(img));
    }
})();
`
}

// RenderMarkdown renders a thread as markdown
func RenderMarkdown(thread *Thread) (string, error) {
	var sb strings.Builder

	sb.WriteString("# ")
	sb.WriteString(thread.Title)
	sb.WriteString("\n\n")

	sb.WriteString("**@")
	sb.WriteString(thread.Author.Username)
	sb.WriteString("** • ")
	sb.WriteString(fmt.Sprintf("%d tweets\n\n", len(thread.Tweets)))
	sb.WriteString("---\n\n")

	for i, tweet := range thread.Tweets {
		sb.WriteString(fmt.Sprintf("## Tweet %d\n\n", i+1))
		sb.WriteString(tweet.Text)
		sb.WriteString("\n\n")

		sb.WriteString("**By:** [@")
		sb.WriteString(tweet.Author.Username)
		sb.WriteString("](https://x.com/")
		sb.WriteString(tweet.Author.Username)
		sb.WriteString(")\n\n")

		sb.WriteString("**Date:** ")
		sb.WriteString(tweet.CreatedAt.Format("January 2, 2006 at 3:04 PM"))
		sb.WriteString("\n\n")

		if len(tweet.Attachments.Media) > 0 {
			sb.WriteString("**Media:**\n")
			for _, media := range tweet.Attachments.Media {
				sb.WriteString("- [")
				sb.WriteString(strings.ToTitle(media.Type))
				sb.WriteString("](")
				sb.WriteString(media.URL)
				sb.WriteString(")\n")
			}
			sb.WriteString("\n")
		}

		if len(tweet.Attachments.URLs) > 0 {
			sb.WriteString("**Links:**\n")
			for _, u := range tweet.Attachments.URLs {
				sb.WriteString("- ")
				sb.WriteString(u)
				sb.WriteString("\n")
			}
			sb.WriteString("\n")
		}

		sb.WriteString("---\n\n")
	}

	sb.WriteString("[View on X/Twitter](")
	sb.WriteString(thread.URL)
	sb.WriteString(")\n")

	return sb.String(), nil
}

// RenderJSON renders a thread as JSON
func RenderJSON(thread *Thread) (string, error) {
	data, err := json.MarshalIndent(thread, "", "  ")
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// EmbedImageAsDataURL converts an image URL to a data URL
func EmbedImageAsDataURL(imageURL string) (string, error) {
	resp, err := http.Get(imageURL)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	contentType := resp.Header.Get("Content-Type")
	if contentType == "" {
		contentType = "image/jpeg"
	}

	dataURL := fmt.Sprintf("data:%s;base64,%s", contentType, encodeBase64(body))
	return dataURL, nil
}

// encodeBase64 encodes bytes as base64
func encodeBase64(data []byte) string {
	const base64chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
	var result strings.Builder

	for i := 0; i < len(data); i += 3 {
		b1 := data[i]
		var b2, b3 byte
		if i+1 < len(data) {
			b2 = data[i+1]
		}
		if i+2 < len(data) {
			b3 = data[i+2]
		}

		result.WriteByte(base64chars[b1>>2])
		result.WriteByte(base64chars[((b1&0x03)<<4)|((b2&0xf0)>>4)])

		if i+1 < len(data) {
			result.WriteByte(base64chars[((b2&0x0f)<<2)|((b3&0xc0)>>6)])
		} else {
			result.WriteByte('=')
		}

		if i+2 < len(data) {
			result.WriteByte(base64chars[b3&0x3f])
		} else {
			result.WriteByte('=')
		}
	}

	return result.String()
}
