// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: categories.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countActiveCategories = `-- name: CountActiveCategories :one
SELECT COUNT(*) FROM categories WHERE deleted_at IS NULL
`

func (q *Queries) CountActiveCategories(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveCategories)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, name, icon, budget, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, name, icon, budget, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	Icon      string        `json:"icon"`
	Budget    sql.NullInt64 `json:"budget"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Budget,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, name, icon, budget, created_at, updated_at, deleted_at FROM categories WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByName = `-- name: GetCategoryByName :one
SELECT id, name, icon, budget, created_at, updated_at, deleted_at FROM categories WHERE name = ? AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByName(ctx context.Context, name string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryByName, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryIncludingDeleted = `-- name: GetCategoryIncludingDeleted :one
SELECT id, name, icon, budget, created_at, updated_at, deleted_at FROM categories WHERE id = ?
`

func (q *Queries) GetCategoryIncludingDeleted(ctx context.Context, id string) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategoryIncludingDeleted, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Icon,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, name, icon, budget, created_at, updated_at, deleted_at FROM categories WHERE deleted_at IS NULL ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Budget,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesUpdatedSince = `-- name: ListCategoriesUpdatedSince :many
SELECT id, name, icon, budget, created_at, updated_at, deleted_at FROM categories WHERE updated_at > ?
`

func (q *Queries) ListCategoriesUpdatedSince(ctx context.Context, updatedAt int64) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesUpdatedSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Budget,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconcileCategoryByName = `-- name: ReconcileCategoryByName :exec
UPDATE categories
SET id = ?, name = ?, icon = ?, budget = ?, deleted_at = ?, updated_at = ?
WHERE id = ?
`

type ReconcileCategoryByNameParams struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	Icon      string        `json:"icon"`
	Budget    sql.NullInt64 `json:"budget"`
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID_2      string        `json:"id_2"`
}

func (q *Queries) ReconcileCategoryByName(ctx context.Context, arg ReconcileCategoryByNameParams) error {
	_, err := q.db.ExecContext(ctx, reconcileCategoryByName,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Budget,
		arg.DeletedAt,
		arg.UpdatedAt,
		arg.ID_2,
	)
	return err
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteCategoryParams struct {
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) SoftDeleteCategory(ctx context.Context, arg SoftDeleteCategoryParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteCategory, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const updateCategory = `-- name: UpdateCategory :exec
UPDATE categories SET name = ?, icon = ?, budget = ?, updated_at = ? WHERE id = ?
`

type UpdateCategoryParams struct {
	Name      string        `json:"name"`
	Icon      string        `json:"icon"`
	Budget    sql.NullInt64 `json:"budget"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error {
	_, err := q.db.ExecContext(ctx, updateCategory,
		arg.Name,
		arg.Icon,
		arg.Budget,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
