// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: expenses.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (id, client_id, amount, currency, category_id, description, merchant, date, source, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, client_id, amount, currency, category_id, description, merchant, date, source, created_at, updated_at, deleted_at
`

type CreateExpenseParams struct {
	ID          string `json:"id"`
	ClientID    string `json:"client_id"`
	Amount      int64  `json:"amount"`
	Currency    string `json:"currency"`
	CategoryID  string `json:"category_id"`
	Description string `json:"description"`
	Merchant    string `json:"merchant"`
	Date        int64  `json:"date"`
	Source      string `json:"source"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRowContext(ctx, createExpense,
		arg.ID,
		arg.ClientID,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.Description,
		arg.Merchant,
		arg.Date,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.Description,
		&i.Merchant,
		&i.Date,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpenseByClientID = `-- name: GetExpenseByClientID :one
SELECT id, client_id, amount, currency, category_id, description, merchant, date, source, created_at, updated_at, deleted_at FROM expenses WHERE client_id = ?
`

func (q *Queries) GetExpenseByClientID(ctx context.Context, clientID string) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseByClientID, clientID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.Description,
		&i.Merchant,
		&i.Date,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT id, client_id, amount, currency, category_id, description, merchant, date, source, created_at, updated_at, deleted_at FROM expenses WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetExpenseByID(ctx context.Context, id string) (Expense, error) {
	row := q.db.QueryRowContext(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.Description,
		&i.Merchant,
		&i.Date,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT e.id, e.client_id, e.amount, e.currency, e.category_id, e.description, e.merchant, e.date, e.source, e.created_at, e.updated_at, e.deleted_at, c.name AS category_name
FROM expenses e
LEFT JOIN categories c ON e.category_id = c.id
WHERE e.deleted_at IS NULL
ORDER BY e.date DESC, e.created_at DESC
`

type ListExpensesRow struct {
	ID           string         `json:"id"`
	ClientID     string         `json:"client_id"`
	Amount       int64          `json:"amount"`
	Currency     string         `json:"currency"`
	CategoryID   string         `json:"category_id"`
	Description  string         `json:"description"`
	Merchant     string         `json:"merchant"`
	Date         int64          `json:"date"`
	Source       string         `json:"source"`
	CreatedAt    int64          `json:"created_at"`
	UpdatedAt    int64          `json:"updated_at"`
	DeletedAt    sql.NullInt64  `json:"deleted_at"`
	CategoryName sql.NullString `json:"category_name"`
}

func (q *Queries) ListExpenses(ctx context.Context) ([]ListExpensesRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesRow
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.Description,
			&i.Merchant,
			&i.Date,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CategoryName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesUpdatedSince = `-- name: ListExpensesUpdatedSince :many
SELECT id, client_id, amount, currency, category_id, description, merchant, date, source, created_at, updated_at, deleted_at FROM expenses WHERE updated_at > ?
`

func (q *Queries) ListExpensesUpdatedSince(ctx context.Context, updatedAt int64) ([]Expense, error) {
	rows, err := q.db.QueryContext(ctx, listExpensesUpdatedSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.Description,
			&i.Merchant,
			&i.Date,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reassignExpensesCategory = `-- name: ReassignExpensesCategory :exec
UPDATE expenses SET category_id = ? WHERE category_id = ?
`

type ReassignExpensesCategoryParams struct {
	CategoryID   string `json:"category_id"`
	CategoryID_2 string `json:"category_id_2"`
}

func (q *Queries) ReassignExpensesCategory(ctx context.Context, arg ReassignExpensesCategoryParams) error {
	_, err := q.db.ExecContext(ctx, reassignExpensesCategory, arg.CategoryID, arg.CategoryID_2)
	return err
}

const softDeleteExpense = `-- name: SoftDeleteExpense :exec
UPDATE expenses SET deleted_at = ?, updated_at = ? WHERE id = ? AND deleted_at IS NULL
`

type SoftDeleteExpenseParams struct {
	DeletedAt sql.NullInt64 `json:"deleted_at"`
	UpdatedAt int64         `json:"updated_at"`
	ID        string        `json:"id"`
}

func (q *Queries) SoftDeleteExpense(ctx context.Context, arg SoftDeleteExpenseParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteExpense, arg.DeletedAt, arg.UpdatedAt, arg.ID)
	return err
}

const sumExpensesByCategory = `-- name: SumExpensesByCategory :many
SELECT e.category_id, c.name AS category_name, SUM(e.amount) AS total
FROM expenses e
LEFT JOIN categories c ON e.category_id = c.id
WHERE e.deleted_at IS NULL AND e.date >= ? AND e.date < ?
GROUP BY e.category_id
`

type SumExpensesByCategoryParams struct {
	Date   int64 `json:"date"`
	Date_2 int64 `json:"date_2"`
}

type SumExpensesByCategoryRow struct {
	CategoryID   string          `json:"category_id"`
	CategoryName sql.NullString  `json:"category_name"`
	Total        sql.NullFloat64 `json:"total"`
}

func (q *Queries) SumExpensesByCategory(ctx context.Context, arg SumExpensesByCategoryParams) ([]SumExpensesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, sumExpensesByCategory, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumExpensesByCategoryRow
	for rows.Next() {
		var i SumExpensesByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.CategoryName, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :exec
UPDATE expenses SET amount = ?, currency = ?, category_id = ?, description = ?, merchant = ?, date = ?, updated_at = ? WHERE id = ?
`

type UpdateExpenseParams struct {
	Amount      int64  `json:"amount"`
	Currency    string `json:"currency"`
	CategoryID  string `json:"category_id"`
	Description string `json:"description"`
	Merchant    string `json:"merchant"`
	Date        int64  `json:"date"`
	UpdatedAt   int64  `json:"updated_at"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) error {
	_, err := q.db.ExecContext(ctx, updateExpense,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.Description,
		arg.Merchant,
		arg.Date,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
