// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
)

type Category struct {
	ID        string        `json:"id"`
	ClientID  string        `json:"client_id"`
	Name      string        `json:"name"`
	Icon      string        `json:"icon"`
	Budget    sql.NullInt64 `json:"budget"`
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
	DeletedAt sql.NullInt64 `json:"deleted_at"`
}

type Expense struct {
	ID          string        `json:"id"`
	ClientID    string        `json:"client_id"`
	Amount      int64         `json:"amount"`
	Currency    string        `json:"currency"`
	CategoryID  string        `json:"category_id"`
	Description string        `json:"description"`
	Merchant    string        `json:"merchant"`
	Date        int64         `json:"date"`
	Source      string        `json:"source"`
	CreatedAt   int64         `json:"created_at"`
	UpdatedAt   int64         `json:"updated_at"`
	DeletedAt   sql.NullInt64 `json:"deleted_at"`
}
