// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recurring_expenses.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createRecurringExpense = `-- name: CreateRecurringExpense :exec
INSERT INTO recurring_expenses (id, amount, currency, category_id, description, merchant, frequency, day_of_month, start_date, end_date, next_run_date, last_run_date, created_at, updated_at, deleted_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRecurringExpenseParams struct {
	ID          string        `json:"id"`
	Amount      int64         `json:"amount"`
	Currency    string        `json:"currency"`
	CategoryID  string        `json:"category_id"`
	Description string        `json:"description"`
	Merchant    string        `json:"merchant"`
	Frequency   string        `json:"frequency"`
	DayOfMonth  sql.NullInt64 `json:"day_of_month"`
	StartDate   int64         `json:"start_date"`
	EndDate     sql.NullInt64 `json:"end_date"`
	NextRunDate int64         `json:"next_run_date"`
	LastRunDate sql.NullInt64 `json:"last_run_date"`
	CreatedAt   int64         `json:"created_at"`
	UpdatedAt   int64         `json:"updated_at"`
	DeletedAt   sql.NullInt64 `json:"deleted_at"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) error {
	_, err := q.db.ExecContext(ctx, createRecurringExpense,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.Description,
		arg.Merchant,
		arg.Frequency,
		arg.DayOfMonth,
		arg.StartDate,
		arg.EndDate,
		arg.NextRunDate,
		arg.LastRunDate,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}

const getRecurringExpense = `-- name: GetRecurringExpense :one
SELECT id, amount, currency, category_id, description, merchant, frequency, day_of_month, start_date, end_date, next_run_date, last_run_date, created_at, updated_at, deleted_at
FROM recurring_expenses
WHERE id = ?
`

func (q *Queries) GetRecurringExpense(ctx context.Context, id string) (RecurringExpense, error) {
	row := q.db.QueryRowContext(ctx, getRecurringExpense, id)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.CategoryID,
		&i.Description,
		&i.Merchant,
		&i.Frequency,
		&i.DayOfMonth,
		&i.StartDate,
		&i.EndDate,
		&i.NextRunDate,
		&i.LastRunDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertRecurringExpenseRun = `-- name: InsertRecurringExpenseRun :exec
INSERT OR IGNORE INTO recurring_expense_runs (id, recurring_expense_id, expense_id, occurrence_date, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertRecurringExpenseRunParams struct {
	ID                 string `json:"id"`
	RecurringExpenseID string `json:"recurring_expense_id"`
	ExpenseID          string `json:"expense_id"`
	OccurrenceDate     int64  `json:"occurrence_date"`
	CreatedAt          int64  `json:"created_at"`
}

func (q *Queries) InsertRecurringExpenseRun(ctx context.Context, arg InsertRecurringExpenseRunParams) error {
	_, err := q.db.ExecContext(ctx, insertRecurringExpenseRun,
		arg.ID,
		arg.RecurringExpenseID,
		arg.ExpenseID,
		arg.OccurrenceDate,
		arg.CreatedAt,
	)
	return err
}

const insertRecurringExpenseRunExpense = `-- name: InsertRecurringExpenseRunExpense :exec
INSERT OR IGNORE INTO expenses (id, amount, currency, category_id, description, merchant, date, source, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, 'recurring', ?, ?)
`

type InsertRecurringExpenseRunExpenseParams struct {
	ID          string `json:"id"`
	Amount      int64  `json:"amount"`
	Currency    string `json:"currency"`
	CategoryID  string `json:"category_id"`
	Description string `json:"description"`
	Merchant    string `json:"merchant"`
	Date        int64  `json:"date"`
	CreatedAt   int64  `json:"created_at"`
	UpdatedAt   int64  `json:"updated_at"`
}

func (q *Queries) InsertRecurringExpenseRunExpense(ctx context.Context, arg InsertRecurringExpenseRunExpenseParams) error {
	_, err := q.db.ExecContext(ctx, insertRecurringExpenseRunExpense,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.Description,
		arg.Merchant,
		arg.Date,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listDueRecurringExpenses = `-- name: ListDueRecurringExpenses :many
SELECT id, amount, currency, category_id, description, merchant, frequency, day_of_month, start_date, end_date, next_run_date, last_run_date, created_at, updated_at, deleted_at
FROM recurring_expenses
WHERE deleted_at IS NULL AND next_run_date <= ? AND (end_date IS NULL OR end_date >= next_run_date)
ORDER BY next_run_date
LIMIT 500
`

func (q *Queries) ListDueRecurringExpenses(ctx context.Context, nextRunDate int64) ([]RecurringExpense, error) {
	rows, err := q.db.QueryContext(ctx, listDueRecurringExpenses, nextRunDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringExpense
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.Description,
			&i.Merchant,
			&i.Frequency,
			&i.DayOfMonth,
			&i.StartDate,
			&i.EndDate,
			&i.NextRunDate,
			&i.LastRunDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringExpensesUpdatedSince = `-- name: ListRecurringExpensesUpdatedSince :many
SELECT id, amount, currency, category_id, description, merchant, frequency, day_of_month, start_date, end_date, next_run_date, last_run_date, created_at, updated_at, deleted_at
FROM recurring_expenses
WHERE updated_at > ?
`

func (q *Queries) ListRecurringExpensesUpdatedSince(ctx context.Context, updatedAt int64) ([]RecurringExpense, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringExpensesUpdatedSince, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringExpense
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.CategoryID,
			&i.Description,
			&i.Merchant,
			&i.Frequency,
			&i.DayOfMonth,
			&i.StartDate,
			&i.EndDate,
			&i.NextRunDate,
			&i.LastRunDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringExpense = `-- name: UpdateRecurringExpense :exec
UPDATE recurring_expenses
SET amount = ?, currency = ?, category_id = ?, description = ?, merchant = ?, frequency = ?, day_of_month = ?, start_date = ?, end_date = ?, next_run_date = ?, last_run_date = ?, updated_at = ?, deleted_at = ?
WHERE id = ?
`

type UpdateRecurringExpenseParams struct {
	Amount      int64         `json:"amount"`
	Currency    string        `json:"currency"`
	CategoryID  string        `json:"category_id"`
	Description string        `json:"description"`
	Merchant    string        `json:"merchant"`
	Frequency   string        `json:"frequency"`
	DayOfMonth  sql.NullInt64 `json:"day_of_month"`
	StartDate   int64         `json:"start_date"`
	EndDate     sql.NullInt64 `json:"end_date"`
	NextRunDate int64         `json:"next_run_date"`
	LastRunDate sql.NullInt64 `json:"last_run_date"`
	UpdatedAt   int64         `json:"updated_at"`
	DeletedAt   sql.NullInt64 `json:"deleted_at"`
	ID          string        `json:"id"`
}

func (q *Queries) UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) error {
	_, err := q.db.ExecContext(ctx, updateRecurringExpense,
		arg.Amount,
		arg.Currency,
		arg.CategoryID,
		arg.Description,
		arg.Merchant,
		arg.Frequency,
		arg.DayOfMonth,
		arg.StartDate,
		arg.EndDate,
		arg.NextRunDate,
		arg.LastRunDate,
		arg.UpdatedAt,
		arg.DeletedAt,
		arg.ID,
	)
	return err
}

const updateRecurringExpenseRunDates = `-- name: UpdateRecurringExpenseRunDates :exec
UPDATE recurring_expenses
SET last_run_date = ?, next_run_date = ?, updated_at = ?
WHERE id = ?
`

type UpdateRecurringExpenseRunDatesParams struct {
	LastRunDate sql.NullInt64 `json:"last_run_date"`
	NextRunDate int64         `json:"next_run_date"`
	UpdatedAt   int64         `json:"updated_at"`
	ID          string        `json:"id"`
}

func (q *Queries) UpdateRecurringExpenseRunDates(ctx context.Context, arg UpdateRecurringExpenseRunDatesParams) error {
	_, err := q.db.ExecContext(ctx, updateRecurringExpenseRunDates,
		arg.LastRunDate,
		arg.NextRunDate,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
