// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sync_state.sql

package sqlc

import (
	"context"
)

const getCurrentServerVersion = `-- name: GetCurrentServerVersion :one
SELECT current_version FROM sync_state WHERE id = 1
`

func (q *Queries) GetCurrentServerVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentServerVersion)
	var current_version int64
	err := row.Scan(&current_version)
	return current_version, err
}

const nextServerVersion = `-- name: NextServerVersion :one
UPDATE sync_state
SET current_version = current_version + 1
WHERE id = 1
RETURNING current_version
`

func (q *Queries) NextServerVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextServerVersion)
	var current_version int64
	err := row.Scan(&current_version)
	return current_version, err
}
