// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet_suggestions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const acceptWalletSuggestion = `-- name: AcceptWalletSuggestion :execresult
UPDATE wallet_suggestions
SET status = 'accepted',
    linked_expense_id = ?1,
    updated_at = ?2,
    client_updated_at = ?3
WHERE id = ?4 AND status = 'pending'
`

type AcceptWalletSuggestionParams struct {
	LinkedExpenseID sql.NullString `json:"linked_expense_id"`
	UpdatedAt       int64          `json:"updated_at"`
	ClientUpdatedAt int64          `json:"client_updated_at"`
	ID              string         `json:"id"`
}

func (q *Queries) AcceptWalletSuggestion(ctx context.Context, arg AcceptWalletSuggestionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, acceptWalletSuggestion,
		arg.LinkedExpenseID,
		arg.UpdatedAt,
		arg.ClientUpdatedAt,
		arg.ID,
	)
}

const createWalletSuggestion = `-- name: CreateWalletSuggestion :exec
INSERT OR IGNORE INTO wallet_suggestions (
    id, amount, currency, merchant, card_name, captured_at, source, status,
    created_at, updated_at, client_updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?, ?)
`

type CreateWalletSuggestionParams struct {
	ID              string         `json:"id"`
	Amount          sql.NullInt64  `json:"amount"`
	Currency        string         `json:"currency"`
	Merchant        string         `json:"merchant"`
	CardName        sql.NullString `json:"card_name"`
	CapturedAt      int64          `json:"captured_at"`
	Source          string         `json:"source"`
	CreatedAt       int64          `json:"created_at"`
	UpdatedAt       int64          `json:"updated_at"`
	ClientUpdatedAt int64          `json:"client_updated_at"`
}

// INSERT OR IGNORE gives us idempotency on the client-supplied id: the Apple
// Pay Shortcut posts the same UUID on retry, the server inserts once and
// silently no-ops thereafter. Callers should follow with GetWalletSuggestion
// to read back the canonical row (whether freshly inserted or pre-existing).
func (q *Queries) CreateWalletSuggestion(ctx context.Context, arg CreateWalletSuggestionParams) error {
	_, err := q.db.ExecContext(ctx, createWalletSuggestion,
		arg.ID,
		arg.Amount,
		arg.Currency,
		arg.Merchant,
		arg.CardName,
		arg.CapturedAt,
		arg.Source,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ClientUpdatedAt,
	)
	return err
}

const dismissWalletSuggestion = `-- name: DismissWalletSuggestion :execresult
UPDATE wallet_suggestions
SET status = 'dismissed',
    updated_at = ?1,
    client_updated_at = ?2
WHERE id = ?3 AND status = 'pending'
`

type DismissWalletSuggestionParams struct {
	UpdatedAt       int64  `json:"updated_at"`
	ClientUpdatedAt int64  `json:"client_updated_at"`
	ID              string `json:"id"`
}

func (q *Queries) DismissWalletSuggestion(ctx context.Context, arg DismissWalletSuggestionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, dismissWalletSuggestion, arg.UpdatedAt, arg.ClientUpdatedAt, arg.ID)
}

const getWalletSuggestion = `-- name: GetWalletSuggestion :one
SELECT id, amount, currency, merchant, card_name, captured_at, source, status,
       linked_expense_id, created_at, updated_at, client_updated_at, server_version
FROM wallet_suggestions
WHERE id = ?
`

func (q *Queries) GetWalletSuggestion(ctx context.Context, id string) (WalletSuggestion, error) {
	row := q.db.QueryRowContext(ctx, getWalletSuggestion, id)
	var i WalletSuggestion
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Merchant,
		&i.CardName,
		&i.CapturedAt,
		&i.Source,
		&i.Status,
		&i.LinkedExpenseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientUpdatedAt,
		&i.ServerVersion,
	)
	return i, err
}

const listWalletSuggestionsByStatus = `-- name: ListWalletSuggestionsByStatus :many
SELECT id, amount, currency, merchant, card_name, captured_at, source, status,
       linked_expense_id, created_at, updated_at, client_updated_at, server_version
FROM wallet_suggestions
WHERE status = ?
ORDER BY captured_at DESC, id DESC
`

func (q *Queries) ListWalletSuggestionsByStatus(ctx context.Context, status string) ([]WalletSuggestion, error) {
	rows, err := q.db.QueryContext(ctx, listWalletSuggestionsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletSuggestion
	for rows.Next() {
		var i WalletSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.Merchant,
			&i.CardName,
			&i.CapturedAt,
			&i.Source,
			&i.Status,
			&i.LinkedExpenseID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientUpdatedAt,
			&i.ServerVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletSuggestionsSinceServerVersion = `-- name: ListWalletSuggestionsSinceServerVersion :many
SELECT id, amount, currency, merchant, card_name, captured_at, source, status,
       linked_expense_id, created_at, updated_at, client_updated_at, server_version
FROM wallet_suggestions
WHERE server_version > ?
`

func (q *Queries) ListWalletSuggestionsSinceServerVersion(ctx context.Context, serverVersion int64) ([]WalletSuggestion, error) {
	rows, err := q.db.QueryContext(ctx, listWalletSuggestionsSinceServerVersion, serverVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WalletSuggestion
	for rows.Next() {
		var i WalletSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Currency,
			&i.Merchant,
			&i.CardName,
			&i.CapturedAt,
			&i.Source,
			&i.Status,
			&i.LinkedExpenseID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientUpdatedAt,
			&i.ServerVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletSuggestionFromSync = `-- name: UpdateWalletSuggestionFromSync :one
UPDATE wallet_suggestions
SET status = ?1,
    linked_expense_id = ?2,
    updated_at = ?3,
    client_updated_at = ?4,
    server_version = ?5
WHERE id = ?6
RETURNING id, amount, currency, merchant, card_name, captured_at, source, status,
          linked_expense_id, created_at, updated_at, client_updated_at, server_version
`

type UpdateWalletSuggestionFromSyncParams struct {
	Status          string         `json:"status"`
	LinkedExpenseID sql.NullString `json:"linked_expense_id"`
	UpdatedAt       int64          `json:"updated_at"`
	ClientUpdatedAt int64          `json:"client_updated_at"`
	ServerVersion   int64          `json:"server_version"`
	ID              string         `json:"id"`
}

func (q *Queries) UpdateWalletSuggestionFromSync(ctx context.Context, arg UpdateWalletSuggestionFromSyncParams) (WalletSuggestion, error) {
	row := q.db.QueryRowContext(ctx, updateWalletSuggestionFromSync,
		arg.Status,
		arg.LinkedExpenseID,
		arg.UpdatedAt,
		arg.ClientUpdatedAt,
		arg.ServerVersion,
		arg.ID,
	)
	var i WalletSuggestion
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Merchant,
		&i.CardName,
		&i.CapturedAt,
		&i.Source,
		&i.Status,
		&i.LinkedExpenseID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientUpdatedAt,
		&i.ServerVersion,
	)
	return i, err
}
